[tool.mypy]
ignore_missing_imports = true

[tool.pyright]
reportMissingTypeStubs = false
reportMissingImports = false

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
  "fastapi.Form",
  "fastapi.File",
  "fastapi.Depends",
  "fastapi.Body",
  "fastapi.Query",
  "fastapi.Path",
  "fastapi.Header",
  "fastapi.Cookie",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "civsa"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["civsa*"]
exclude = ["tests*", "scripts*"]